title: Club de Go Nantes Yosakura
description: "Site internet du club de Go Nantes Yosakura."
baseurl: ""
url: "https://nantes.jeudego.org"
endpoint_url: "https://nantes-tournament.appspot.com"
association_name: "Yosakura Club de Go de Nantes"
email: "clubyosakura@yahoo.fr"
president: "Marc JÃ©gou"

markdown: kramdown
plugins:
  - jemoji
theme: minima
permalink: pretty
show_excerpts: True
excerpt_separator: <!--more-->
